### ISSUE TITLE
Sunrise Sunset Times

### ISSUE THREAD

**Issue by Yeshia** [weather-gov/api#41]
Do any of the API endpoints provide the Sunset and Sunrise time for that day?

Thanks

**Comment by netbymatt** [comment]
No they don't. I was looking for this some time ago when I was putting together my app. I was working in Javascript so I used https://github.com/mourner/suncalc to get that data. It's a fairly easy integration since you're either searching by Lat/Lon, or can get the Lat/Lon from one of the API calls and then pass that to the suncalc library to get sunrise and sunset.

**Comment by StephenClouse** [comment]
Correct, it's not something we currently expose. We do actually calculate it internally, because it's needed for some metadata bits on the forecast and observation endpoints, but we don't output the actual times anywhere.

I'm honestly not really sure where it would fit. Maybe a whole new endpoint. Suggestions welcome.

**Comment by Yeshia** [comment]
Perhaps in the daily forecast endpoint? Seems like it might make sense there.

**Comment by StephenClouse** [comment]
Maybe, but the forecast isn't actually daily, it's semi-daily (12-hour periods, 6-6), and sunrise/sunset don't always fit neatly into those boxes, especially as we get around the solstices.

And don't even get me started on Alaska.

Still, it's something we'll try to think about.
